-- Employee Table
CREATE TABLE EMPLOYEE (
    EMP_ID SERIAL PRIMARY KEY,
    EMP_LName VARCHAR(255) NOT NULL,
    EMP_FName VARCHAR(255) NOT NULL,
    EMP_gender VARCHAR(50) NOT NULL,
    EMP_CIN VARCHAR(255) NOT NULL,
    EMP_email VARCHAR(255),
    EMP_street VARCHAR(255) NOT NULL,
    EMP_zipCode VARCHAR(255) NOT NULL,
    EMP_city VARCHAR(255) NOT NULL,
    EMP_salary DECIMAL(10, 2) NOT NULL
);

-- Patient Table
CREATE TABLE PATIENT (
    PATIENT_ID SERIAL PRIMARY KEY NOT NULL,
    PATIENT_FName VARCHAR(255) NOT NULL,
    PATIENT_LName VARCHAR(255) NOT NULL,
    PATIENT_phoneNum VARCHAR(255) NOT NULL,
    PATIENT_dateOfBirth DATE NOT NULL,
    PATIENT_sex VARCHAR(50) NOT NULL,
    PATIENT_email VARCHAR(255),
    PATIENT_CIN VARCHAR(255) NOT NULL,
    PATIENT_city VARCHAR(255) NOT NULL,
    PATIENT_street VARCHAR(255) NOT NULL
);


-- Document Table
CREATE TABLE DOCUMENT (
    DOC_ID SERIAL PRIMARY KEY NOT NULL,
    DOC_TYPE VARCHAR(255) CHECK (DOC_TYPE IN ('CERTIFICATE', 'PRESCRIPTION')) NOT NULL,
    DOC_date DATE,
    DOC_desc TEXT,
    EMP_ID INT,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

-- Certificate Table
CREATE TABLE CERTIFICATE (
    DOC_ID INT PRIMARY KEY,
    cert_duration INT NOT NULL,
    EMP_ID INT,
    FOREIGN KEY (DOC_ID) REFERENCES DOCUMENT(DOC_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
) INHERITS (DOCUMENT);

-- Medicine Table
CREATE TABLE MEDICINE (
    MED_serial_num VARCHAR(255) PRIMARY KEY,
    MED_name VARCHAR(255) NOT NULL,
    MED_expDate DATE NOT NULL,
    MED_prodDate DATE,
    MED_amount INT NOT NULL
);


-- Prescription Table
CREATE TABLE PRESCRIPTION (
    DOC_ID INT PRIMARY KEY,
    Presc_desc TEXT NOT NULL,
    MED_serial_num VARCHAR(255),
    EMP_ID INT,
    FOREIGN KEY (DOC_ID) REFERENCES DOCUMENT(DOC_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
	FOREIGN KEY (MED_serial_num) REFERENCES MEDICINE(MED_serial_num)
	ON DELETE CASCADE
	ON UPDATE CASCADE
) INHERITS (DOCUMENT);


-- Bill Table
CREATE TABLE BILL (
    BILL_ID SERIAL PRIMARY KEY,
    BILL_total DECIMAL(10, 2),
    BILL_desc TEXT NOT NULL,
    EMP_ID INT,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

-- Appointment Table
CREATE TABLE APPOINTMENT (
    APT_ID SERIAL PRIMARY KEY NOT NULL,
    APT_date DATE NOT NULL,
    APT_status VARCHAR(255) NOT NULL,
    PATIENT_ID INT,
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

-- Payment Table
CREATE TABLE PAYMENT (
    PMNT_ID SERIAL PRIMARY KEY,
    PMNT_CC_exp_date DATE NOT NULL,
    PMNT_CC_CVV VARCHAR(255) NOT NULL,
    PMNT_QTY INT NOT NULL,
    PMNT_amount DECIMAL(10, 2),
    PMNT_date DATE NOT NULL,
    APT_ID INT,
    MED_serial_num VARCHAR(255),
    PATIENT_ID INT,
    BILL_ID INT,
    FOREIGN KEY (APT_ID) REFERENCES APPOINTMENT(APT_ID),
    FOREIGN KEY (MED_serial_num) REFERENCES MEDICINE(MED_serial_num),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    FOREIGN KEY (BILL_ID) REFERENCES BILL(BILL_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

-- Provider Table
CREATE TABLE PROVIDER (
    PROV_ID SERIAL PRIMARY KEY,
    PROV_name VARCHAR(255) NOT NULL,
    PROV_street VARCHAR(255),
    PROV_zipCode VARCHAR(255),
    PROV_city VARCHAR(255)
);

-- Stock Table
CREATE TABLE STOCK (
    PROV_ID INT,
    MED_serial_num VARCHAR(255),
    STOCK_itemQty INT NOT NULL,
    STOCK_dateAdded DATE NOT NULL,
    PRIMARY KEY (PROV_ID, MED_serial_num),
    FOREIGN KEY (PROV_ID) REFERENCES PROVIDER(PROV_ID),
    FOREIGN KEY (MED_serial_num) REFERENCES MEDICINE(MED_serial_num)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

-- Session Table
CREATE TABLE SESSION (
    SES_ID SERIAL PRIMARY KEY,
    SES_duration INT,
    APT_ID INT,
    EMP_ID INT,
    FOREIGN KEY (APT_ID) REFERENCES APPOINTMENT(APT_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

